### ISSUE TITLE
Undo?

### ISSUE THREAD

**Issue by mgrider** [TN1ck/super-sudoku#10]
I don't really use the mouse, so occasionally I'll hit the wrong number, and need to undo what I just did. My instinct is to hit cmd-z (I'm on a mac), but that doesn't actually work... but what if it did?

Also, once or twice I've started down a path, adding or removing notes, and then realize that I was mistaken, and wanted to undo a few moves in a row, so it should probably be a full undo buffer if possible.

This is kind of an over-the-top request, I know, but I thought I'd file it anyway. 😁

**Comment by TN1ck** [comment]
Cool suggestion! The application architecture will actually allow this to be added rather painlessly, will hopefully have time in a few weeks.

**Comment by mgrider** [comment]
Nice! 💪

**Comment by TN1ck** [comment]
@mgrider I just implemented it, let me know if this works for you!

**Comment by mgrider** [comment]
@TN1ck Working great! Really impressive!

**Comment by TN1ck** [comment]
@mgrider Awesome! Changed it a bit more by moving the position in the menu after I saw someone play it (#12)
