### ISSUE TITLE
debian-live-11.6 build with 'yarn install'

### ISSUE THREAD

**Issue by tux2bsd** [TN1ck/super-sudoku#2]
using debian-live-11.6 VM as a "clean room" build (I don't use/trust `yarn` so needed somewhere to try it)

download your code zip file, extract, cd into it

`yarn install` fails, the first solution in following URL gets past that problem ( https://stackoverflow.com/questions/46013544/yarn-install-command-error-no-such-file-or-directory-install ), this is what that solution was:

```
sudo apt remove cmdtest
sudo apt remove yarn
curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
sudo apt-get update
sudo apt-get install yarn -y
```

Then this occurred:

```
user@debian:~/Downloads/super-sudoku-master$ yarn install
yarn install v1.22.19
[1/4] Resolving packages...
[2/4] Fetching packages...
error @vitejs/plugin-react@2.0.1: The engine "node" is incompatible with this module. Expected version "^14.18.0 || >=16.0.0". Got "12.22.5"
error Found incompatible module.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

I realise this is likely not _your_ issue but it's quite common for developers to have an environment where building stuff is 2nd nature.  This may show up something of interest.

**Comment by TN1ck** [comment]
Hey thanks for the report! I will work on the docs and provide a more clear step by step installation. Probably drop yarn in the process as it's not necessary.

**Comment by TN1ck** [comment]
@tux2bsd I improved the README a bit and removed the mention of yarn. If you have nodejs installed, npm is also installed, which simplifies the setup.

**Comment by TN1ck** [comment]
I close this as `npm` is now the package manager of choice here for now (install doesn't take long enough to warrant pnpm) and there is also now a docker image provided.
