### ISSUE TITLE
Edit auto-generated notes

### ISSUE THREAD

**Issue by lelandbatey** [TN1ck/super-sudoku#7]
I'm hoping for some way to edit the notes generated by the "Show auto-generated notes" toggle. For example, in the following image I can't remove 2 and 9 candidates from the other cells (the"other cells" are the cells which have 1,4,2,9 in them) in the center 3x3 even though logically I can eliminate the 2&9

![Screenshot_20240502-092250~2](https://github.com/TN1ck/super-sudoku/assets/1964720/c86209ed-6c54-4c13-97b4-3adffd960549)

----------

On more difficult sudokus when playing with "show generated notes" turned on, sometimes I want to alter the notes that are visible, even though they're generated. Right now, if the "show generated notes" is on, I can't change the notes in the squares. Usually I just deal with not being able to change the notes, but sometimes I will get desperate. In those times, I'll have to manually copy all the generated notes to the "normal notes"/"user notes" and *then* make my changes to the notes. But then I lose the ability for future correct guesses to be automatically tracked in the notes.

I'd like some way to be able to turn on auto-generated notes while also being able to change those auto-generated notes somehow. I realize though that might be quite annoying to implement.

If I were to speculate about implementing this feature (I've not looked at the code) the most complete solution seems like you'd have to track both the auto-generated notes and the users changes to those notes and reconcile them *somehow*; maybe via a kind of "layer" system.

A potentially easier but less comprehensive implementation would be a button labeled something like "copy auto-generated notes into user notes" which does a one-time copy of the auto-notes to the notes which are editable by the user when the the button is clicked. This approach would cut out the step I described where I manually copy the auto-notes, but that'd still leave me to manually manage the notes going forward. Though I suppose manually managing the notes would be much easier now that I've got a buttong that does a one-way sync from auto-notes to user notes...

Anyway, thank you again for such a snappy, polished, accessible, and fun sudoku implementation!

**Comment by TN1ck** [comment]
Thank you for the detailed request, I will get to it in the next weeks.

**Comment by TN1ck** [comment]
You are right, the best way is to reconcile both the auto and manual notes.

I think the best is to make to:

* Add a notion of added / rejected note, currently the notes are just a list of numbers
* With that I can make the auto generated notes be be preselected for the user and they can reject them
* When the auto generated notes change, the rejected notes will still be there and I can remove them from the auto generated notes

I think there is no value in showing a manual note that is already rejected by the auto notes, so I will make sure those cannot be selected.

**Comment by TN1ck** [comment]
@lelandbatey Actually it was easier. I'm not doing a reconciliation, but instead I use the auto generated notes as a starting point for the user notes when they set one. I added some highlighting of notes on the buttons to make this more obvious. When all user notes are deselected, the auto notes are used again for that specific cell. Let me know if this works as expected or if some behaviour is unusual / could be improved.

**Comment by lelandbatey** [comment]
I love this change, it allows me to remove auto-generated notes just like I asked. Thank you so much for making this change!
